import { TagCloud } from "./tagCloud";
import MASK from "./panda.png";
const $container: HTMLElement = document.querySelector("#app")!;

const tagCloud = new TagCloud($container, {
  width: 333,
  height: 300,
  maskImage: MASK,
  debug: true,
  minFontSize: 10,
  maxFontSize: 100,
  angleCount: 3,
  angleFrom: -90,
  angleTo: 90,
  pixelRatio: 4,
  cut: false,
  padding: 3,
});

// tagCloud.shape((ctx: CanvasRenderingContext2D) => {
//   ctx.arc(250,250,100,0, Math.PI * 2);
//   ctx.fill()
// });

tagCloud.draw([
  { text: "aaaaaa laaa", weight: 100, color: "red" },
  { text: " fff ", weight: 100, color: "blue" },
  { text: "   www   ", weight: 100, color: "blue" },
  { text: "www www", weight: 100, color: "blue" },
  { text: "wwwwww", weight: 100, color: "blue" },
  { text: "wwwwww", weight: 100, color: "blue" },
  { text: "wwwwww", weight: 100, color: "blue" },
  // { text: "ab", weight: 110 },
  // { text: "ac", weight: 90 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  { text: "〇", weight: 100, color: "red" },

  // { text: "afds", weight: 10 },
  // { text: "ab", weight: 110 },
  // { text: "ac", weight: 90 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  // { text: "afds", weight: 10 }, { text: "ab", weight: 110 },
  // { text: "ac", weight: 90 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 }, { text: "ab", weight: 110 },
  { text: "ac", weight: 90 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 }, { text: "ab", weight: 110 },
  { text: "ac", weight: 90 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 }, { text: "ab", weight: 110 },
  { text: "ac", weight: 90 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 }, { text: "ab", weight: 110 },
  { text: "ac", weight: 90 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 },
  { text: "agdfgdfg", weight: 10 },
  { text: "awerwer", weight: 50 },
  { text: "aflf", weight: 10 },
  { text: "afsoufsaf", weight: 10 },
  { text: "adfgdsg", weight: 10 },
  { text: "asf", weight: 10 },
  { text: "xsdfa", weight: 20 },
  { text: "adf", weight: 10 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 },
  { text: "agdfgdfg", weight: 10 },
  { text: "awerwer", weight: 50 },
  { text: "aflf", weight: 10 },
  { text: "afsoufsaf", weight: 10 },
  { text: "adfgdsg", weight: 10 },
  { text: "asf", weight: 10 },
  { text: "呵呵打", weight: 20 },
  { text: "adf", weight: 10 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 },
  { text: "agdfgdfg", weight: 10 },
  { text: "awerwer", weight: 50 },
  { text: "aflf", weight: 10 },
  { text: "afsoufsaf", weight: 10 },
  { text: "adfgdsg", weight: 10 },
  { text: "asf", weight: 10 },
  { text: "xsdfa", weight: 20 },
  { text: "adf", weight: 10 },
  { text: "ad", weight: 10 },
  { text: "aaa", weight: 10 },
  { text: "afds", weight: 10 },
  { text: "agdfgdfg", weight: 10 },
  { text: "awerwer", weight: 50 },
  { text: "aflf", weight: 10 },
  { text: "afsoufsaf", weight: 10 },
  { text: "adfgdsg", weight: 10 },
  // { text: "asf", weight: 10 },
  // { text: "xsdfa", weight: 20 },
  // { text: "adf", weight: 10 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  // { text: "afds", weight: 10 },
  // { text: "agdfgdfg", weight: 10 },
  // { text: "awerwer", weight: 50 },
  // { text: "aflf", weight: 10 },
  // { text: "afsoufsaf", weight: 10 },
  // { text: "adfgdsg", weight: 10 },
  // { text: "asf", weight: 10 },
  // { text: "xsdfa", weight: 20 },
  // { text: "adf", weight: 10 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  // { text: "afds", weight: 10 },
  // { text: "agdfgdfg", weight: 10 },
  // { text: "awerwer", weight: 50 },
  // { text: "aflf", weight: 10 },
  // { text: "afsoufsaf", weight: 10 },
  // { text: "adfgdsg", weight: 10 },
  // { text: "asf", weight: 10 },
  // { text: "xsdfa", weight: 20 },
  // { text: "adf", weight: 10 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  // { text: "afds", weight: 10 },
  // { text: "agdfgdfg", weight: 10 },
  // { text: "awerwer", weight: 50 },
  // { text: "aflf", weight: 10 },
  // { text: "afsoufsaf", weight: 10 },
  // { text: "adfgdsg", weight: 10 },
  // { text: "asf", weight: 10 },
  // { text: "xsdfa", weight: 20 },
  // { text: "adf", weight: 10 },
  // { text: "ad", weight: 10 },
  // { text: "aaa", weight: 10 },
  // { text: "afds", weight: 10 },
  // { text: "agdfgdfg", weight: 10 },
  // { text: "awerwer", weight: 50 },
  // { text: "aflf", weight: 10 },
  // { text: "afsoufsaf", weight: 10 },
  // { text: "adfgdsg", weight: 10 },
  // { text: "asf", weight: 10 },
  // { text: "xsdfa", weight: 20 },
  // { text: "adf", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "dgdfga", weight: 10 },
  // { text: "adfa", weight: 10 },
  // { text: "asdffg", weight: 10 }
]);
